### ISSUE TITLE
How to disable intrinsics optimization?

### ISSUE THREAD

**Issue by guillaume-michel** [facebookresearch/DABA#11]
Hi,
I would like to congratulate you on the amazing results you present in your paper.

In my particular problem, I have a single camera with precise intrinsics calibration which is already known. The camera is moving around an object. **I would like to modify DABA, so that intrinsics parameters are not optimized**. In my python prototype (quite slow), I saw that it improves the reconstruction.

For that, I tried to replace line https://github.com/facebookresearch/DABA/blob/main/sfm/ba/functions/ba_functions.h#L151:
```cpp
jac_int.col(0) = extrinsic.col(2);
jac_int.col(0) -= dist.dot(extrinsic.col(2)) /
                    (dist_squared_norm_plus_delta_squared_plus_its_sqrt)*dist;
jac_int.col(0) *= rescaled_sqrt_weight;
jac_int.col(1) = jac_int.col(0) * radical_squared;
jac_int.col(2) = jac_int.col(1) * radical_squared;
```
by 
```cpp
jac_int.setZero();
```

and on line https://github.com/facebookresearch/DABA/blob/main/sfm/ba/functions/ba_functions.h#L223 replaced:
```cpp
jac_int.col(0) = SQRT_TWO * rescaled_sqrt_weight * extrinsic.col(2);
jac_int.col(1) = radical_squared * jac_int.col(0);
jac_int.col(2) = radical_squared * jac_int.col(1);
```
by:
```cpp
jac_int.setZero();
```

It is my understanding that `jac_int` is the part of jacobian related to intrinsics and setting it to zero should in practice disable intrinsics optimization but unfortunately, intrinsics parameters are still changing from iteration to iteration.

Is there a way to disable intrinsics optimization? 

As a side question, Could you details what the `UpdateIntrinsicsHelper` method does at line https://github.com/facebookresearch/DABA/blob/main/sfm/ba/functions/ba_functions.h#L617? I have trouble identifying what `H` and `grad` are.

Thank you so much for your help.
Best regards

**Comment by guillaume-michel** [comment]
To answer my own question, It is also necessary to disable proximal intrinsics resolution.

**Comment by WindowsXp-Beta** [comment]
May I ask your environment settings in order to compile DABA? I tried following its README but it turned out that some functions in thrust have been removed and some header files are missing so it couldn't get successfully compiled.
