### ISSUE TITLE
It can solve pose graph error also?

### ISSUE THREAD

**Issue by Nick-Heo** [facebookresearch/DABA#3]
If I add pose graph error and jacobians, it can solve also?

I don't have the knowledge about mpi / nccl. so I don't know about it works well.

 I want to know DABA solve pose graph problems, when I use your api about Least square optimization.

Thank you.

**Comment by fantaosha** [comment]
Thanks for your interests in your work. Unfortunately, DABA currently does not support pose graph factors. But we might add this feature in the future.

**Comment by mhmukadam** [comment]
@fantaosha I think @Nick-Heo might already have plans to add pose graph factors. If they do, are there any other modifications needed?
