### ISSUE TITLE
some problems when visualizing the poses and points

### ISSUE THREAD

**Issue by CarminLiu** [facebookresearch/DABA#9]
Hi,

First,  thanks for your great work.

Because I'm not sure what tool to use to visualize the results, so I transform the "results-mm-lm-acc-trivial-problem-1723-156502-pre-2-GPU-1000-iters.txt" to the colmap format(which save r_{iw}, t_{iw}, p_w).

In my understand, "results-mm-....txt" saves:
 [R_{wi} | R_{wi}t_{iw} = -t_{wi}] 
f k1 k2
-p_w1 -p_w2 -p_w3

After I have transformed the poses and points, I got a weird result.
![image](https://github.com/facebookresearch/DABA/assets/22850971/1d95383f-437d-403a-bf17-1e17c14558f0)
(after optimization)
this is the code I try to transform
```
  extrinsic.resize(num_extrinsics);
  for (int i = 0; i < num_extrinsics; i++) {
    std::getline(file, line);
    Eigen::Matrix<double, 3, 3> r;
    Eigen::Vector3d t;
    for (int m = 0; m < 3; m++) {
      std::getline(file, line);
      std::istringstream iss(line);
      iss >> r.coeffRef(m, 0) >> r.coeffRef(m, 1) >> r.coeffRef(m, 2) >> t[m];
    }
    // if r is r_wi
    // t_iw = - r_wi^T * t_iw =r_wi^T  *( - t_wi) = r_wi^T * t
    Eigen::Vector3d r_aa;
    Log(r.transpose(), r_aa); // copy from DABA/sfm/math/
    t = r * t;
    Eigen::AngleAxisd r_aad(r_aa.norm(), r_aa.normalized());
    Eigen::Quaterniond qua(r_aad);
    qua.normalize();
    qua.inverse();

    extrinsic[i].resize(7);
    extrinsic[i][0] = qua.w();
    extrinsic[i][1] = qua.x();
    extrinsic[i][2] = qua.y();
    extrinsic[i][3] = qua.z();

    for (int m = 0; m < 3; m++) {
      extrinsic[i][m + 4] = t[m];
    }
  }
  ```

I transform the input "problem-1723-156502-pre.txt", and I got the correct result:
![image](https://github.com/facebookresearch/DABA/assets/22850971/36caa75b-72b5-4ecd-8123-c7b00aa1ec4e)

I did modified you code, and i just run command`mpiexec -n 2 ./bin/mpi_daba_bal_dataset --dataset /path/to/your/dataset --iters 1000 --loss "trivial" --accelerated true --save true`.

I don't know where I got a misunderstanding. And I also want to know if there is a tool to visualiza the results easily. 

Thank you!

**Comment by fantaosha** [comment]
Hello,

Sorry for the late reply. I haven't tested visualization in colmap but according to the [initialization code](https://github.com/facebookresearch/DABA/blob/db4ee72e014f21e7177424fc47ea24fc18827073/sfm/ba/dataset.cu#L132), it think the correct output format for colmap visualization might be `Eigen::Matrix3d R=g.leftCols<3>().transpose()` and `Eigen::Vector3d t = g.leftCols<3>().transpose() * g.col(3)`. Please let me know if this works for you. Thanks!
